### ISSUE TITLE
[Sync Test Infra] Setup Fenix Sync Integration Test job on Jenkins

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/mobile-test-eng#294]
@isabelrios @AaronMT I'd also suggest to touch base with Amedyne to see if we'd like to setup a slack channel like firefox-ios-alerts ... perhaps, fenix-alerts ??

**Comment by AaronMT** [comment]
Current issue with a `pipenv check`.

```+ pipenv check
Checking PEP 508 requirements...
Passed!
Checking installed package safety...
[JSONParseError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
[JSONParseError]:       return ctx.invoke(self.callback, **ctx.params)
[JSONParseError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
[JSONParseError]:       return callback(*args, **kwargs)
[JSONParseError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/decorators.py", line 73, in new_func
[JSONParseError]:       return ctx.invoke(f, obj, *args, **kwargs)
[JSONParseError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
[JSONParseError]:       return callback(*args, **kwargs)
[JSONParseError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/cli/command.py", line 514, in check
[JSONParseError]:       do_check(
[JSONParseError]:   File "/usr/local/lib/python3.9/site-packages/pipenv/core.py", line 2692, in do_check
[JSONParseError]:       raise exceptions.JSONParseError(c.out, c.err)
Failed parsing JSON results:
ERROR: Pipenv encountered a problem and had to exit.
ERROR TEXT: Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/safety/__main__.py", line 51, in <module>
    cli(prog_name="safety")
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/safety/cli.py", line 63, in check
    import pkg_resources
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1367
    raise SyntaxError(e) from e
                            ^
SyntaxError: invalid syntax
```

Not entirely sure what the issue is here but first thing I would like to try is removing this line, and then trying pipenv update

https://github.com/mozilla-mobile/fenix/blob/master/app/src/androidTest/java/org/mozilla/fenix/syncintegration/Pipfile#L22

**Comment by AaronMT** [comment]
Notes so far

* Pixel emulator with Hardware GPU needs to be selected or else 'System UI is not responding' messages are shown (even this is not guaranteed) [HAXM installed, 2GB too low? (https://stackoverflow.com/questions/61037149/system-ui-is-not-responding-error-message-in-android-studio)]
* Pixel emulator session needs a cold boot and should not be saved (in Snapshot settings) or else a prompt to quick resume is always shown
* https://github.com/mozilla-mobile/fenix/blob/master/app/src/androidTest/java/org/mozilla/fenix/syncintegration/gradlewbuild.py#L24 Gradle task is now ```connectedAndroidDebugTest```
*  New AVD needs to be changed in https://github.com/mozilla-mobile/fenix/blob/master/app/src/androidTest/java/org/mozilla/fenix/syncintegration/launchSimScript.sh#L5 as well as SDK locations


It takes a long time for the emulator to be ready and Fenix is never installed.

**Comment by AaronMT** [comment]
Updating androidx-test (to bypass https://github.com/android/android-test/issues/902) yields warnings treated as errors in. Not sure if these need to changed, or if we can ignore these somehow?

```Kotlin
> Task :app:compileDebugAndroidTestKotlin FAILED
e: warnings found and -Werror specified
w: /Users/administrator/Downloads/fenix/app/src/androidTest/java/org/mozilla/fenix/glean/BaselinePingTest.kt: (11, 27): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/administrator/Downloads/fenix/app/src/androidTest/java/org/mozilla/fenix/glean/BaselinePingTest.kt: (71, 23): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/administrator/Downloads/fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt: (10, 27): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/administrator/Downloads/fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt: (28, 5): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/administrator/Downloads/fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/IdlingResourceHelper.kt: (4, 27): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/administrator/Downloads/fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/IdlingResourceHelper.kt: (11, 65): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/administrator/Downloads/fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/IdlingResourceHelper.kt: (19, 67): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/administrator/Downloads/fenix/app/src/androidTest/java/org/mozilla/fenix/screenshots/DefaultHomeScreenTest.kt: (8, 27): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/administrator/Downloads/fenix/app/src/androidTest/java/org/mozilla/fenix/screenshots/DefaultHomeScreenTest.kt: (24, 28): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/administrator/Downloads/fenix/app/src/androidTest/java/org/mozilla/fenix/screenshots/MenuScreenShotTest.kt: (11, 27): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/administrator/Downloads/fenix/app/src/androidTest/java/org/mozilla/fenix/screenshots/MenuScreenShotTest.kt: (41, 28): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
```

**Comment by isabelrios** [comment]
Some more notes you may already know... I think the issue might come with the new android studio... I can launch both ui and sync integration tests from command line with 4.1.1 with this command: `./gradlew app:connectedDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=org.mozilla.fenix.ui.HomeScreenTest#homeScreenItemsTest`
but same command fails on 4.1.3. 
Launching both kind of tests from Android Studio works, tests start as they should without that screen. 

Not sure if downloading an older version could be an option to try...

**Comment by isabelrios** [comment]
> https://github.com/mozilla-mobile/fenix/blob/master/app/src/androidTest/java/org/mozilla/fenix/syncintegration/gradlewbuild.py#L24 Gradle task is now connectedAndroidDebugTest

I think the correct task is `connectedDebugAndroidTest` or `connectedAndroidTest`

**Comment by AaronMT** [comment]
Notes:
* Landed the gradlewbuild.py change above
* Swapping to API 28 starts up a run with the least amount of issues 
* Running into test failures now (PR's up)
