### ISSUE TITLE
Wire up parse-ui-test.py for Focus Android once Task Graph landed

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/mobile-test-eng#469]

**Comment by AaronMT** [comment]
```Log
[task 2021-09-15T19:07:20.692Z] 
[task 2021-09-15T19:07:20.746Z] Traceback (most recent call last):
[task 2021-09-15T19:07:20.746Z]   File "./automation/taskcluster/androidTest/parse-ui-test.py", line 62, in <module>
[task 2021-09-15T19:07:20.746Z]     main()
[task 2021-09-15T19:07:20.746Z]   File "./automation/taskcluster/androidTest/parse-ui-test.py", line 58, in main
[task 2021-09-15T19:07:20.746Z]     print("| {matrixId} | {outcome} | [logs]({webLink}) | {axes[0][details]}\n".format(**matrix_result))
[task 2021-09-15T19:07:20.746Z] IndexError: list index out of rang
```

**Comment by AaronMT** [comment]
This might be resolved with enabling Cloud Tools Results API for moz-focus-android as the artifacts were't available prior to enabling it just now.

**Comment by AaronMT** [comment]
This works now.
