### ISSUE TITLE
Fix DISABLED test: saveLoginFromPromptTest

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#478]
saveLoginFromPromptTest

java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.openThreeDotMenu(HomeScreenRobot.kt:173)
at org.mozilla.fenix.ui.SettingsPrivacyTest.saveLoginFromPromptTest(SettingsPrivacyTest.kt:206)

**Comment by AndiAJ** [comment]
Closed with [#21439](https://github.com/mozilla-mobile/fenix/pull/21439)
