### ISSUE TITLE
Fix DISABLED test: openExternalLinksInPrivateTest

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/mobile-test-eng#480]
openExternalLinksInPrivateTest

Note: no code change

[Isabel] also saw failing locally. Appears to be a timing issue.

[Andi] failing here: }.openTabDrawer {

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.test.uiautomator.UiObject2.click()' on a null object reference
at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openTabDrawer(BrowserRobot.kt:506)
at org.mozilla.fenix.ui.SettingsPrivacyTest.openExternalLinksInPrivateTest(SettingsPrivacyTest.kt:282)

**Comment by sv-ohorvath** [comment]
Will be fixed with https://github.com/mozilla-mobile/fenix/pull/21518
