### ISSUE TITLE
Focus/Fenix UI tests do not run on API30+ [dep upgrade & ActivityScenarioRule implementation required]

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/mobile-test-eng#602]
Currently, Focus/Fenix UI tests do not run on API30+ (as discovered by jalmeida)

```Kotlin
E  java.lang.IllegalArgumentException: Wrong number of arguments; expected 6, got 3
E      at java.lang.reflect.Method.invoke(Native Method)
E      at androidx.test.services.speakeasy.client.ToolConnection$ToolConnectionPostIcs.doCall(ToolConnection.java:197)
E      at androidx.test.services.speakeasy.client.ToolConnection.publish(ToolConnection.java:79)
E      at androidx.test.services.speakeasy.client.ToolConnection.publish(ToolConnection.java:69)
E      at androidx.test.services.shellexecutor.BlockingPublish.getResult(BlockingPublish.java:74)
E      at androidx.test.services.shellexecutor.ShellCommandExecutorServer.start(ShellCommandExecutorServer.java:80)
E      at androidx.test.services.shellexecutor.ShellMain.main(ShellMain.java:45)
E      at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
E      at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
E  Error reporting crash
E  java.lang.RuntimeException: Bad file descriptor
E      at android.os.BinderProxy.transactNative(Native Method)
E      at android.os.BinderProxy.transact(BinderProxy.java:540)
E      at android.app.IActivityManager$Stub$Proxy.handleApplicationCrash(IActivityManager.java:5182)
E      at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:158)
E      at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
E      at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
E      at java.lang.Thread.dispatchUncaughtException(Thread.java:2203)
I  Sending signal. PID: 19230 SIG: 9
```

I am guessing that all Android testing dependencies would need to be updated. 

https://developer.android.com/jetpack/androidx/releases/test

``ext.espresso_version = '3.1.0-alpha4'`` to 3.4.0
``androidTestUtil 'androidx.test:orchestrator:1.2.0' `` to 1.4.1
``androidTestImplementation 'androidx.test:runner:1.2.0'`` to 1.4.0
``testImplementation 'androidx.test:rules:1.2.0'`` to 1.4.0

and adding ``testImplementation 'androidx.test.services:test-services:1.4.1'``

and then modifying the Flank configurations to run on API30.

Note API30 seems to be the upper API ceiling on virtual devices (it also seems to be a beta still).

```Shell
│ Pixel2            │ Google             │ Pixel 2                             │ VIRTUAL  │ 1920 x 1080 │ 26,27,28,29,30          │ beta=30        │
│ Pixel3            │ Google             │ Pixel 3                             │ VIRTUAL  │ 2160 x 1080 │ 30                      │ beta=30        │
```

Unknowns: If upgrades require app configuration changes too and test breakage afterwards.

**Comment by AaronMT** [comment]
**Focus**

Record keeping

Current environment on API 29 AVD (local test-run: [results](https://github.com/mozilla-mobile/mobile-test-eng/files/7928435/API29-Results.zip))
![Screen Shot 2022-01-24 at 2 50 55 PM](https://user-images.githubusercontent.com/102331/150854151-0cd597c0-725e-4140-8318-0c6c9b026645.png)

**Comment by AaronMT** [comment]
With API 30 (AVD) and an upgraded environment attempting to run the `androidTest` suite yields:

``ext.espresso_version = '3.4.0'``
``testImplementation 'androidx.test:rules:1.4.0'``
``androidTestImplementation 'androidx.test:runner:1.4.0'``
``androidTestUtil 'androidx.test:orchestrator:1.4.1'``

Note, we will also need `androidTestImplementation 'androidx.test.ext:junit-ktx:1.1.3'` in `app/build.gradle`

```Kotlin
w: ATTENTION!
This build uses unsafe internal compiler arguments:

-XXLanguage:+NonParenthesizedAnnotationsOnFunctionalTypes

This mode is not recommended for production use,
as no stability/compatibility guarantees are given on
compiler or generated code. Use it at your own risk!

e: warnings found and -Werror specified
w: /Users/aaronmt/Mozilla/focus-android/app/src/androidTest/java/org/mozilla/focus/activity/CustomTabTest.kt: (19, 27): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/aaronmt/Mozilla/focus-android/app/src/androidTest/java/org/mozilla/focus/activity/CustomTabTest.kt: (47, 28): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/aaronmt/Mozilla/focus-android/app/src/androidTest/java/org/mozilla/focus/helpers/MainActivityTestRule.kt: (10, 43): 'IntentsTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/aaronmt/Mozilla/focus-android/app/src/androidTest/java/org/mozilla/focus/helpers/MainActivityTestRule.kt: (12, 27): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/aaronmt/Mozilla/focus-android/app/src/androidTest/java/org/mozilla/focus/helpers/MainActivityTestRule.kt: (29, 5): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/aaronmt/Mozilla/focus-android/app/src/androidTest/java/org/mozilla/focus/helpers/MainActivityTestRule.kt: (59, 5): 'IntentsTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/aaronmt/Mozilla/focus-android/app/src/androidTest/java/org/mozilla/focus/screenshots/FirstRunScreenshots.kt: (7, 27): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/aaronmt/Mozilla/focus-android/app/src/androidTest/java/org/mozilla/focus/screenshots/FirstRunScreenshots.kt: (20, 28): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/aaronmt/Mozilla/focus-android/app/src/androidTest/java/org/mozilla/focus/screenshots/HomeScreenScreenshots.kt: (16, 27): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/aaronmt/Mozilla/focus-android/app/src/androidTest/java/org/mozilla/focus/screenshots/HomeScreenScreenshots.kt: (34, 28): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/aaronmt/Mozilla/focus-android/app/src/androidTest/java/org/mozilla/focus/screenshots/SettingsScreenshots.kt: (9, 27): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
w: /Users/aaronmt/Mozilla/focus-android/app/src/androidTest/java/org/mozilla/focus/screenshots/SettingsScreenshots.kt: (24, 28): 'ActivityTestRule<T : Activity!>' is deprecated. Deprecated in Java
```

https://developer.android.com/reference/androidx/test/rule/ActivityTestRule

> This class is deprecated.
use ActivityScenario or ActivityScenarioRule instead. They offer a simpler, and safer way of controlling Activity lifecycles.

I believe we need to convert to using https://developer.android.com/reference/androidx/test/ext/junit/rules/ActivityScenarioRule which is an upgraded version of the now deprecated `ActivityTestRule`. The tricky part will be ensuring we handle all the before and after activity logic we currently have (e.g, skip first run) using the new rules. As `ActivityScenarioRule` is marked `final` it's not a straight-forward swap in our test rule Classes which inherited `ActivityTestRule`

Blog on some examples
https://medium.com/stepstone-tech/better-tests-with-androidxs-activityscenario-in-kotlin-part-1-6a6376b713ea

**Comment by AaronMT** [comment]
Permission problem on API30
https://developer.android.com/about/versions/11/privacy/storage#permissions-target-11

**Comment by AaronMT** [comment]
This is nearing landing on Fenix.
